# Generated by Django 4.2.4 on 2023-08-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование объекта')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='telegramm name работника')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='chat id telegram')),
                ('rate', models.FloatField(verbose_name='Зарплата работника в час (в рублях)')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(help_text='Пример ввода данных - 2022-01-01', verbose_name='Год - Месяц - Число')),
                ('start_work', models.TimeField(help_text='Пример ввода данных -  09:00', verbose_name='Время начала рабочего дня')),
                ('end_work', models.TimeField(help_text='Пример ввода данных -  19:00', verbose_name='Время окончания рабочего дня')),
                ('lunch', models.TimeField(help_text='Пример ввода данных -  01:00', verbose_name='Время обеда')),
                ('work_time', models.FloatField(verbose_name='Чисто время работы (за вычетом обеда)')),
                ('salary_per_day', models.FloatField(verbose_name='Зарплата за текущую дату')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.object', verbose_name='Объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Поьзователь')),
            ],
        ),
    ]
